GlobalPlanner:
  use_dijkstra: true 
  use_astar: false  
  use_quadratic: true 
  use_grid_path: false  
  old_navfn_behavior: false  
  allow_unknown: false  # Cambiato da true a false per evitare pianificazione attraverso aree sconosciute
  default_tolerance: 0.0  
  planner_window_x: 8.0  
  planner_window_y: 8.0  
  cost_factor: 1.5  # Aumentato per dare più peso agli ostacoli
  orientation_mode: 1  
  neutral_cost: 80  
  lethal_cost: 255  
  outline_map: true  
  publish_potential: true  # Aggiungi questa opzione per pubblicare la mappa dei potenziali
  visualize_potential: true  # Aggiungi questa per visualizzare in RViz