global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: false
  width: 10.0
  height: 10.0
  resolution: 0.05
  track_unknown_space: true # Add this line to track unknown space
  static_map: true
  observation_persistence: 0.0  
          
  # plugins:
  #   - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # static_layer:
  #   map_topic: map
  #   subscribe_to_updates: true
  #   track_unknown_space: true
  #   use_maximum: false
  #   unknown_cost_value: 255
  #   lethal_cost_threshold: 100
  #   map_file: /home/alterego-base/catkin_ws/src/AlterEGO_v2/navigation_stack/config/maps/office/demo1_exclusions.pgm  # Path to your map file
  #   origin: [0.0, 0.0, 0.0]
  #   resolution: 0.05

  # obstacle_layer:
  #   observation_sources: laser_scan_sensor
  #   laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  # inflation_layer:
  #   inflation_radius: 0.5