GlobalPlanner:
  use_dijkstra: true  # Usa l'algoritmo di Dijkstra per la pianificazione globale
  use_grid_path: false  # Usa un percorso a griglia
  old_navfn_behavior: false  # Usa il comportamento vecchio di NavFn
  allow_unknown: true  # Permetti il passaggio attraverso celle sconosciute
  default_tolerance: 0.0  # Tolleranza predefinita per il goal
  planner_window_x: 0.0  # Dimensione della finestra del planner lungo l'asse x
  planner_window_y: 0.0  # Dimensione della finestra del planner lungo l'asse y
  cost_factor: 3.0  # Fattore di costo per la pianificazione
  orientation_mode: 1  # Modalità di orientamento (0: nessuna, 1: lungo il percorso, 2: verso il goal)