local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  observation_persistence: 0.0
  static_map: false        # Nessuna mappa statica per la costmap locale


# plugins:
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# obstacle_layer:
#   enable: true
#   observation_sources: laser_scan_sensor
#   laser_scan_sensor: 
#     sensor_frame: laser_link
#     data_type: LaserScan
#     topic: scan
#     marking: true                 
#     clearing: true
#     observation_persistence: 0.0
#     expected_update_rate: 0.083  # Reflects the 12 Hz update rate
#     max_obstacle_height: 1.0

# inflation_layer:
#   enable: true
#   inflation_radius: 0.5
#   cost_scaling_factor: 10.0 # Abbassa se vuoi permettere al robot di avvicinarsi di più agli ostacoli