Locations:
  - KIT cabinet:
      position:
        x: 16.56
        y: -0.86
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.85
        w: 0.51
  - KIT dishwasher:
      position:
        x: 10.16
        y: -1.72
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.14
        w: 1.0
  - KIT table:
      position:
        x: -0.12
        y: -4.10
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.094
        w: 1.0
  - KIT kitchen:
      position:
        x: -0.12
        y: -4.10
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.094
        w: 1.0
  - DLR cabinet:
      position:
        x: 2.08
        y: -4.63
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.88
        w: 0.45
  - DLR dishwasher:
      position:
        x: 10.94
        y: -5.81
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.70
        w: 0.70
  - DlR table:
      position:
        x: 4.17
        y: -7.5
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.91
        w: 0.40
  - DLR kitchen:
      position:
        x: 14.883840888212323
        y: -5.577089035415129
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.7438358928243373
        w: 0.6683623003627756
  - INRIA cabinet:
      position:
        x: 5.827440901268306
        y: -7.203600478412124
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.30965125545923355
        w: 0.9508501985026456
  - INRIA dishwasher:
      position:
        x: 8.3575399702214
        y: -1.23
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.9964198849974955
        w: 0.08454237269900815
  - INRIA table:
      position:
        x: 8.3575399702214
        y: -1.23
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.9964198849974955
        w: 0.08454237269900815
  - INRIA kitchen:
      position:
        x: 8.3575399702214
        y: -1.23
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.9964198849974955
        w: 0.08454237269900815
  - Door KIT-INRIA: #Door Sud 
      position:
        x: 16.56
        y: -0.86
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.85
        w: 0.51
  - Door INRIA-KIT:  #Door Nord
    position:
      x: 16.56
      y: -0.86
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.85
      w: 0.51