Locations:
  - Ingresso:
      position:
        x: 17.40
        y: -0.25
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 1
        w: 0.12
  - Porto di Genova:
      position:
        x: 10.16
        y: -1.72
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.14
        w: 1.0
  - Navi Mercantili:
      position:
        x: -0.12
        y: -4.10
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.094
        w: 1.0
  - Emigrazione:
      position:
        x: 2.08
        y: -4.63
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.88
        w: 0.45
  - Navi Militari:
      position:
        x: 10.94
        y: -5.81
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.70
        w: 0.70
  - Navi Transatlantiche:
      position:
        x: 4.17
        y: -7.5
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.91
        w: 0.40
        